export const SET_FIRSTNAME = "SET_FIRSTNAME";
export const SET_LASTNAME = "SET_LASTNAME";
export const SET_USEREMAIL = "SET_USEREMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_CONFIRMPASSWORD = "SET_CONFIRMPASSWORD";